-- ═══════════════════════════════════════════════════════════════════════════
-- Kriegswabwehr – ISP-Missbrauchsmeldung / ISP Abuse Reporter
-- ═══════════════════════════════════════════════════════════════════════════
-- LEGAL: Automatische Meldung an ISP-Missbrauchskontakte gemäß RFC 5965 ARF.
--        Dies ist von der Internet-Community ausdrücklich erwünscht und legal.
-- LEGAL: Automatic reporting to ISP abuse contacts per RFC 5965 ARF.
--        This is explicitly encouraged by the internet community and legal.
-- ─────────────────────────────────────────────────────────────────────────────
-- Was passiert: Wenn ein Angreifer Stufe 3 erreicht, wird automatisch:
--   1. Ein RFC-5965-konformer Missbrauchsbericht generiert
--   2. Der Bericht an Discord geschickt (zum manuellen Weiterleiten)
--   3. Ein Beweisdossier mit allen Angriffsdaten erstellt
--   4. Eine Referenz-ID für Strafanzeigen generiert
-- What happens: When an attacker reaches level 3, automatically:
--   1. An RFC-5965-compliant abuse report is generated
--   2. The report is sent to Discord (for manual forwarding)
--   3. An evidence dossier with all attack data is created
--   4. A reference ID for police reports is generated
-- ═══════════════════════════════════════════════════════════════════════════

AbuseReporter = {}

-- ─────────────────────────────────────────────────────────────────────────────
-- RDAP / WHOIS Lookup für Missbrauchskontakt
-- RDAP / WHOIS lookup for abuse contact
-- ─────────────────────────────────────────────────────────────────────────────
-- Nutzt das ARIN RDAP-System (öffentlich, kostenlos, legal)
-- Uses the ARIN RDAP system (public, free, legal)

local RDAP_URLS = {
    "https://rdap.arin.net/registry/ip/",
    "https://rdap.lacnic.net/rdap/ip/",
    "https://rdap.db.ripe.net/ip/",
    "https://rdap.apnic.net/ip/",
    "https://rdap.afrinic.net/rdap/ip/",
}

-- ─────────────────────────────────────────────────────────────────────────────
-- Referenz-ID-Generator / Reference ID generator
-- ─────────────────────────────────────────────────────────────────────────────
local function generateRefID(ip)
    local cleanIP = ip:gsub("%.", ""):gsub(":", "")
    local ts      = os.date("%Y%m%d%H%M%S")
    local rand    = string.format("%04X", math.random(0, 65535))
    return string.format("KW-%s-%s-%s", ts:sub(1, 8), cleanIP:sub(1, 6), rand)
end

-- ─────────────────────────────────────────────────────────────────────────────
-- RFC-5965-ARF-Missbrauchsbericht generieren
-- Generate RFC 5965 ARF abuse report
-- ─────────────────────────────────────────────────────────────────────────────
local function buildARFReport(data)
    -- data = { ip, country, isp, asn, attackType, timestamps, violations, refID, serverName, serverIP }
    local serverName = GetConvar("sv_projectName", GetConvar("sv_hostname", "FiveM Server"))
    local ts         = os.date("!%a, %d %b %Y %H:%M:%S +0000")

    local report = table.concat({
        "From: abuse-report@kriegswabwehr.local",
        "To: abuse@" .. (data.isp or "isp.example.com"):lower():gsub("%s+", ""),
        "Date: " .. ts,
        "Subject: [ABUSE] DDoS / Connection Flood Attack - " .. (data.ip or "Unknown") .. " - Ref: " .. data.refID,
        "MIME-Version: 1.0",
        "Content-Type: multipart/report; report-type=feedback-report;",
        '    boundary="KW-BOUNDARY-' .. data.refID .. '"',
        "",
        "--KW-BOUNDARY-" .. data.refID,
        "Content-Type: text/plain; charset=UTF-8",
        "",
        "Dear Abuse Department,",
        "",
        "We are reporting repeated DDoS / connection flood attacks originating from an IP",
        "address within your network. The attacks targeted our game server during the player",
        "connection phase (loading screen), attempting to exhaust connection resources.",
        "",
        "Please investigate and take appropriate action against the responsible customer.",
        "",
        "Attack Details:",
        "  Source IP:       " .. (data.ip or "Unknown"),
        "  Country:         " .. (data.country or "Unknown"),
        "  ISP / Network:   " .. (data.isp or "Unknown"),
        "  ASN:             " .. (data.asn or "Unknown"),
        "  Attack Type:     " .. (data.attackType or "Connection Flood"),
        "  Violations:      " .. tostring(data.violations or 0),
        "  First Seen:      " .. os.date("!%Y-%m-%dT%H:%M:%SZ", data.firstSeen or os.time()),
        "  Last Seen:       " .. os.date("!%Y-%m-%dT%H:%M:%SZ", data.lastSeen or os.time()),
        "  Reference ID:    " .. data.refID,
        "",
        "Target Server:   " .. serverName,
        "",
        "This report was automatically generated by Kriegswabwehr DDoS Protection System.",
        "Full evidence dossier available on request.",
        "",
        "Regards,",
        serverName .. " Administration",
        "",
        "--KW-BOUNDARY-" .. data.refID,
        "Content-Type: message/feedback-report",
        "",
        "Feedback-Type: abuse",
        "User-Agent: Kriegswabwehr/1.0",
        "Version: 1",
        "Original-Mail-From: <connection@" .. (data.ip or "unknown") .. ">",
        "Original-Rcpt-To: <server@kriegswabwehr.local>",
        "Arrival-Date: " .. ts,
        "Source-IP: " .. (data.ip or "Unknown"),
        "Reported-Domain: " .. (data.ip or "Unknown"),
        "",
        "--KW-BOUNDARY-" .. data.refID .. "--",
    }, "\r\n")

    return report
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Beweisdossier generieren / Generate evidence dossier
-- ─────────────────────────────────────────────────────────────────────────────
local function buildDossier(data)
    local serverName = GetConvar("sv_projectName", GetConvar("sv_hostname", "FiveM Server"))
    local lines = {
        "╔══════════════════════════════════════════════════════════════════╗",
        "║          KRIEGSWABWEHR – BEWEISDOSSIER / EVIDENCE DOSSIER       ║",
        "╚══════════════════════════════════════════════════════════════════╝",
        "",
        "Referenz-ID / Reference ID : " .. data.refID,
        "Erstellt / Created          : " .. os.date("!%Y-%m-%d %H:%M:%S UTC"),
        "Server                      : " .. serverName,
        "",
        "══ ANGREIFER-INFORMATIONEN / ATTACKER INFORMATION ══════════════════",
        "IP-Adresse             : " .. (data.ip or "Unbekannt"),
        "Land / Country         : " .. (data.country or "Unbekannt"),
        "Stadt / City           : " .. (data.city or "Unbekannt"),
        "ISP / Anbieter         : " .. (data.isp or "Unbekannt"),
        "ASN                    : " .. (data.asn or "Unbekannt"),
        "Subnetz / Subnet       : " .. (data.subnet or "Unbekannt"),
        "VPN erkannt / Detected : " .. (data.isVPN and "JA / YES" or "NEIN / NO"),
        "Proxy erkannt          : " .. (data.isProxy and "JA / YES" or "NEIN / NO"),
        "Hosting-IP             : " .. (data.isHosting and "JA / YES" or "NEIN / NO"),
        "",
        "══ ANGRIFFSDETAILS / ATTACK DETAILS ════════════════════════════════",
        "Angriffstyp / Type     : " .. (data.attackType or "Connection Flood"),
        "Anzahl Verstöße        : " .. tostring(data.violations or 0),
        "Erster Versuch         : " .. os.date("!%Y-%m-%d %H:%M:%S UTC", data.firstSeen or os.time()),
        "Letzter Versuch        : " .. os.date("!%Y-%m-%d %H:%M:%S UTC", data.lastSeen or os.time()),
        "Maßnahme / Action      : " .. (data.action or "permban"),
        "Subnetz gesperrt       : " .. ((data.subnetBlocked) and "JA / YES" or "NEIN / NO"),
        "",
        "══ VERBINDUNGSZEITSTEMPEL / CONNECTION TIMESTAMPS ══════════════════",
    }

    if data.timestamps and #data.timestamps > 0 then
        for i, ts in ipairs(data.timestamps) do
            if i > 20 then
                table.insert(lines, "  ... (+" .. (#data.timestamps - 20) .. " weitere / more)")
                break
            end
            table.insert(lines, string.format("  #%-3d %s", i, os.date("!%Y-%m-%d %H:%M:%S UTC", ts)))
        end
    else
        table.insert(lines, "  (keine Zeitstempel verfügbar / no timestamps available)")
    end

    table.insert(lines, "")
    table.insert(lines, "══ RECHTLICHE HINWEISE / LEGAL NOTES ══════════════════════════════")
    table.insert(lines, "Dieses Dossier kann als Beweismittel für eine Strafanzeige verwendet")
    table.insert(lines, "werden. Alle Daten wurden automatisch auf dem Zielserver erfasst.")
    table.insert(lines, "This dossier may be used as evidence for a criminal complaint.")
    table.insert(lines, "All data was automatically recorded on the target server.")
    table.insert(lines, "")
    table.insert(lines, "Relevante Gesetze / Relevant laws:")
    table.insert(lines, "  DE: §303b StGB (Computersabotage), §202a StGB (Ausspähen von Daten)")
    table.insert(lines, "  EU: Directive 2013/40/EU on attacks against information systems")
    table.insert(lines, "  US: 18 U.S.C. § 1030 (Computer Fraud and Abuse Act)")
    table.insert(lines, "")
    table.insert(lines, "══════════════════════════════════════════════════════════════════════")

    return table.concat(lines, "\n")
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Öffentliche API / Public API
-- ─────────────────────────────────────────────────────────────────────────────

-- Hauptfunktion: Missbrauchsbericht erstellen und via Discord versenden
-- Main function: create abuse report and send via Discord
function AbuseReporter.report(data)
    -- data = { ip, country, city, isp, asn, subnet, isVPN, isProxy, isHosting,
    --          attackType, violations, firstSeen, lastSeen, timestamps, action, subnetBlocked }

    data.refID = generateRefID(data.ip or "unknown")

    local dossier   = buildDossier(data)
    local arfReport = buildARFReport(data)

    -- Konsolenausgabe / Console output
    Logger.warn("[ABUSE-REPORT] Generiert für / Generated for IP=" .. (data.ip or "?") .. " Ref=" .. data.refID)
    print(dossier)

    -- An Discord senden (als langer Embed + Datei) / Send to Discord (as long embed + file)
    if Config.DiscordWebhook and Config.DiscordWebhook ~= "" then
        -- Dossier-Kurzfassung als Embed / Short dossier as embed
        Logger.sendDiscord(
            "📁 Beweisdossier / Evidence Dossier – " .. data.refID,
            "```\n" .. dossier:sub(1, 3800) .. "\n```",
            Config.DiscordColors.permban,
            {
                { name = "🌐 IP",            value = data.ip or "?",          inline = true  },
                { name = "🗺️ Land",          value = data.country or "?",     inline = true  },
                { name = "🏢 ISP",           value = data.isp or "?",         inline = true  },
                { name = "📋 Ref-ID",        value = data.refID,              inline = true  },
                { name = "⚔️ Angriffstyp",  value = data.attackType or "?",  inline = true  },
                { name = "🔢 Verstöße",      value = tostring(data.violations or 0), inline = true },
                { name = "📨 ARF-Bericht",   value = "Im nächsten Embed / In next embed", inline = false },
            }
        )

        -- ARF-Bericht als separater Embed / ARF report as separate embed
        Wait(500)
        Logger.sendDiscord(
            "📨 RFC-5965-ARF-Missbrauchsbericht / Abuse Report – " .. data.refID,
            "Bitte an **abuse@" .. (data.isp or "isp.example"):lower():gsub("%s+", "") .. "** weiterleiten:\n```\n" .. arfReport:sub(1, 3500) .. "\n```",
            Config.DiscordColors.warning,
            {
                { name = "📬 Senden an / Send to", value = "abuse@" .. (data.isp or "?"):lower():gsub("[^a-z0-9%-%.]+", ""), inline = false },
            }
        )
    end

    return data.refID
end

-- Schnellbericht bei Stufe-3-Eskalation / Quick report on level-3 escalation
function AbuseReporter.quickReport(ip, geoData, violations)
    local geo = geoData or {}
    AbuseReporter.report({
        ip           = ip,
        country      = geo.country or "XX",
        city         = geo.city or "Unknown",
        isp          = geo.isp or "Unknown",
        asn          = geo.asn or "Unknown",
        subnet       = (geo.ip and geo.ip:match("^(%d+%.%d+%.%d+)") or ip:match("^(%d+%.%d+%.%d+)") or "?") .. ".0/24",
        isVPN        = geo.isVPN or false,
        isProxy      = geo.isProxy or false,
        isHosting    = geo.isHosting or false,
        attackType   = "DDoS / Connection Flood (Loading Screen Phase)",
        violations   = violations or 3,
        firstSeen    = os.time(),
        lastSeen     = os.time(),
        action       = "permban + subnet block",
        subnetBlocked = true,
    })
end

Logger.info("AbuseReporter initialisiert / AbuseReporter initialized")
